# Generated by Django 3.2 on 2025-07-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20250705_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_all_day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
    ]
