# Generated by Django 3.2 on 2025-07-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20250705_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='user_agent',
        ),
    ]
