# Generated by Django 3.2 on 2025-07-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20250705_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('FR', 'Fourth Year')], help_text='Select one of: FY, SY, TY, FR', max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_year_links', to='events.academicyear')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_year_links', to='events.event')),
            ],
            options={
                'verbose_name': 'Event–Academic Year Link',
                'verbose_name_plural': 'Event–Academic Year Links',
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(check=models.Q(name__in=['FY', 'SY', 'TY', 'FR']), name='valid_academic_year_name'),
        ),
        migrations.AddField(
            model_name='event',
            name='academic_years',
            field=models.ManyToManyField(related_name='events', through='events.EventAcademicYear', to='events.AcademicYear'),
        ),
        migrations.AlterUniqueTogether(
            name='eventacademicyear',
            unique_together={('event', 'academic_year')},
        ),
    ]
