# Generated by Django 3.2 on 2025-07-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_position'),
    ]

    operations = [
    ]
