# Generated by Django 3.2 on 2025-07-01 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('', '---------'), ('First year', 'First year'), ('Second year', 'Second year'), ('Third year', 'Third year'), ('Fourth year', 'Fourth year')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Core', 'Core'), ('Tech', 'Tech'), ('Web', 'Web'), ('Doc', 'Doc'), ('Event Management', 'Event Management'), ('Media', 'Media')], max_length=50),
        ),
    ]
