# Generated by Django 3.2 on 2025-07-01 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250701_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('', '---------'), ('AI&D', 'AI & Data Science'), ('CS', 'Computer Engineering'), ('IT', 'Information Technology'), ('ENTC', 'Electronics & Telecommunication'), ('ELEC', 'Electrical Engineering'), ('INSTRU', 'Instrumentation Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
